spring:
  cloud:
    gateway:
      httpclient:
        ssl:
          useInsecureTrustManager: true
          handshake-timeout-millis: 10000
          close-notify-flush-timeout-millis: 3000
          close-notify-read-timeout-millis: 0



#---
#  server:
#    port: 9001
#    ssl:
#      enabled: true
#      client-auth: need
#      key-store: classpath:client-app.jks
#      key-store-password: client-app
#      key-alias: client-app
#      key-store-type: JKS
#      key-store-provider: SUN
#      trust-store: classpath:client-app.jks
#      trust-store-password: client-app
#      trust-store-type: JKS
